apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: gameon-gateway
  namespace: gameon-system
spec:
  selector:
    istio: ingressgateway # use istio gateway impl
  servers:
  - port:
      name: http
      number: 80
      protocol: HTTP
    hosts:
    - 'gameon.192.168.99.100.xip.io'
    tls:
      httpsRedirect: true # sends 301 redirect for http requests
  - port:
      number: 443
      name: https
      protocol: HTTPS
    hosts:
    - 'gameon.192.168.99.100.xip.io'
    tls:
      mode: SIMPLE #enables HTTPS on this port
      serverCertificate: /etc/istio/ingressgateway-certs/tls.crt
      privateKey: /etc/istio/ingressgateway-certs/tls.key

