kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: gameon-ingress
  namespace: gameon-system
  annotations: {}

spec:
  backend:
    serviceName: webapp.gameon-system.svc.cluster.local
    servicePort: 8080
# TLS block causes automatic redirection of http -> https
  tls:
  - hosts:
    - GAMEON_INGRESS
    secretName: GAMEON_INGRESS_SECRET
  rules:
  - host: GAMEON_INGRESS
    http:
      paths:
      - path: /auth
        backend:
          serviceName: auth.gameon-system.svc.cluster.local
          servicePort: 9080
      - path: /players
        backend:
          serviceName: player.gameon-system.svc.cluster.local
          servicePort: 9080
      - path: /mediator
        backend:
          serviceName: mediator.gameon-system.svc.cluster.local
          servicePort: 9080
      - path: /map
        backend:
          serviceName: map.gameon-system.svc.cluster.local
          servicePort: 9080
      - path: /rooms
        backend:
          serviceName: room.gameon-system.svc.cluster.local
          servicePort: 9080
      - path: /swagger
        backend:
          serviceName: swagger.gameon-system.svc.cluster.local
          servicePort: 8080
